name = "DocTest"
uuid = "4aafb19d-f9c6-4616-befb-92f64bf8b55b"
authors = ["Miguel Alonso <miguel883@gmail.com>"]
version = "0.1.0"

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CImGui = "6.0.0"
GLFW = "3.4.4"
JSON = "0.21.4"
Random = "1.11.0"
