name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    # These permissions are needed to:
    # - Deploy the documentation: https://documenter.juliadocs.org/stable/man/hosting/#Permissions
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Always the first step to get your code

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.4' # Explicitly request Julia 1.11.x (or '1.11.0' for exact)

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2 # Caches Pkg artifacts for faster builds

      - name: Switch to docs directory
        run: |
            echo "Current working directory: $(pwd)"
            echo "Contents of current directory:"
            ls -F
            cd docs/ # Change directory to the docs folder
            echo "Changed to directory: $(pwd)"
            echo "Contents of docs directory:"
            ls -F

      - run: |
            sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev xsettingsd x11-xserver-utils
      - run: >
          cd docs; # Change to docs directory for the context of this run command
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
          julia --color=yes --project -e 'println(pwd())'

        # DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      # - name: Install dependencies
      #   shell: julia --color=yes --project=. {0} # Note: --project=. here
      #   run: |
      #       using Pkg
      #       Pkg.instantiate()
      #       println(Pkg.status())
    #       Pkg.develop(PackageSpec(path="..")) # ".." refers to the parent (Flight.jl) from docs/

    #   - name: Build and deploy
    #     run: julia --color=yes --project=. make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token